/*
01 Create Account
Create accounts for HR schema
Run this as either SYS or SYSTEM.
*/

DROP DATABASE HR;
DROP ROLE HR CASCADE;
CREATE USER HR IDENTIFIED BY HR;
ALTER ROLE HR WITH LOGIN;
ALTER USER HR WITH CONNECTION LIMIT 20;
GRANT CONNECT TO HR;
CREATE DATABASE HR OWNER HR;
CREATE DATABASE HR WITH OWNER HR ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TABLESPACE "pg_default";
GRANT CONNECT ON DATABASE HR TO HR;
GRANT ALL PRIVILEGES ON DATABASE HR TO HR;
