/*
01 Create Account
Create accounts for HR schema
Run this as either SYS or SYSTEM.
*/

DROP DATABASE HR;
DROP ROLE HR CASCADE;
CREATE USER HR IDENTIFIED BY HR;
ALTER ROLE HR WITH LOGIN;
ALTER USER HR WITH CONNECTION LIMIT 20;
GRANT CONNECT TO HR;
CREATE DATABASE HR OWNER HR;
GRANT CONNECT ON DATABASE HR TO HR;
GRANT ALL PRIVILEGES ON DATABASE HR TO HR;
